### ISSUE TITLE
Unable to build IOS 

### ISSUE THREAD

**Issue by lecicdjuro** [muslimtv/flutter_playout#13]
[!] Unable to determine Swift version for the following pods:

    - `flutter_playout` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of
    the targets that integrate this pod.

**Comment by KhuramKhalid** [comment]
Is your project in objective c?

**Comment by KhuramKhalid** [comment]
I found something similar at this link. Please have a look https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c
