### ISSUE TITLE
Set desired aspect ratio for stream preview

### ISSUE THREAD

**Issue by lecicdjuro** [muslimtv/flutter_playout#17]
I have live stream that is streaming from the phone camera and it has a 9/16 aspect ratio.
Currently, stream view is only in 16 /9 aspect ratio.
Can this be optional, predefined?

**Comment by KhuramKhalid** [comment]
I believe the aspect ratio is entirely controlled by the Dart side of code. So as long as you wrap the Video widget in an AspectRatio widget with 9/16 ratio, it should appear correctly. Please let me know how it goes.

**Comment by lecicdjuro** [comment]
That is that i first tried
