### ISSUE TITLE
crush

### ISSUE THREAD

**Issue by sanjidbillah** [muslimtv/flutter_playout#19]
when i play this audio 

[https://www.jollygul.com/wp-content/uploads/2019/03/Kalaam-e-Mawla-Patience-Gratitude.mp3](url)

apps is crush
![image](https://user-images.githubusercontent.com/54928529/75364207-85934e00-58e5-11ea-964a-587899991879.png)

**Comment by KhuramKhalid** [comment]
Please setup a notification icon named "ic_notification_icon" in your Android project.

**Comment by sanjidbillah** [comment]
yes this is work thanks..

do you have seek?

**Comment by sanjidbillah** [comment]
yes this is works brother thank you <3
