### ISSUE TITLE
Enable non-HLS (progressive) video sources

### ISSUE THREAD

**Issue by skytz** [muslimtv/flutter_playout#27]
Hello,

I needed non HLS support for a project I'm working on.
While I tested this package, iOS was working fine but there was a need for a small change to make it work on Android too.

So I made a pull request with the fix: https://github.com/muslimtv/flutter_playout/pull/26

**Next part is valid only for Android**
One thing to note is that progressive files are quite varied and some of them support seeking while others do not (https://exoplayer.dev/progressive.html). 

One suggestion would be to connect to `onSourceInfoRefreshed` callback on `ProgressiveMediaSource` class and internally change the seek state so that all seek events from the user are ignored. I'm not sure what will happen if you seek and the media does not support that. I guess it crashes.
I'm not doing that now because i don't need it and its out of the scope of this pull request.

If the source is an MP4 file it works without any issues, even if that's a live stream.

**Comment by KhuramKhalid** [comment]
Merged #26 will update on pub.dev now
