### ISSUE TITLE
Crash when play with wrong url!

### ISSUE THREAD

**Issue by phanbaohuy96** [muslimtv/flutter_playout#3]
When i play with url isn't audio link, the app get crash. Can you validate the url in the native platform?

**Comment by KhuramKhalid** [comment]
Try using v1.0.10. Implemented better exception handling so player should not cause the app to crash, instead you should get some reasonable message in onError callback.

**Comment by phanbaohuy96** [comment]
on iOS, i can't play the audio link. Can you check this?

**Comment by KhuramKhalid** [comment]
Please try 1.0.11

**Comment by phanbaohuy96** [comment]
Thanks, i will try and if any happened i will report back to you. Tks for support.

**Comment by phanbaohuy96** [comment]
Some issues happened. That is i play audio and i stop it and then i replay this audio the observer doesn't trigger any event after that a stop it and get crash.

**Comment by KhuramKhalid** [comment]
> Some issues happened. That is i play audio and i stop it and then i replay this audio the observer doesn't trigger any event after that a stop it and get crash on iOS

I'm not able to reproduce this. Are you playing a live stream? Is there anything else you're doing in the callbacks that might cause this? Also please make sure to try on a real device as well. The player doesn't work properly on simulator.
