### ISSUE TITLE
Needs a way to make the player Full Screen Automatically onRotation

### ISSUE THREAD

**Issue by real1900** [muslimtv/flutter_playout#32]
Needs a way to make the player to go Full Screen Automatically onRotation and/ or manually

**Comment by KhuramKhalid** [comment]
I created custom player controls in Dart side and used the below code for making player go fullscreen (on fullscreen icon tap).

```Dart
if (widget.orientation == Orientation.landscape) {
    await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    await SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
} else {
    await SystemChrome.setPreferredOrientations([DeviceOrientation.landscapeLeft]);
    await SystemChrome.setEnabledSystemUIOverlays([]);
}
```

To make player go fullscreen automatically when user rotates the device, I just hide all other widgets from the view except player widget and I also set the width and height of player widget to the screen width and height. That gives the desired effect.

It would be nice to have the Android native player go fullscreen without Dart hacks similar to iOS native player.
