### ISSUE TITLE
[Android]Stream doesn't work

### ISSUE THREAD

**Issue by lecicdjuro** [muslimtv/flutter_playout#39]
The stream that was working on 1.30 version, now isn't working on Android ONLY, while on IOS everything works fine

 Source error.
E/ExoPlayerImplInternal(19268): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
E/ExoPlayerImplInternal(19268): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1095)
E/ExoPlayerImplInternal(19268): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:974)
E/ExoPlayerImplInternal(19268): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(19268): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(19268): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(19268): 	at java.lang.Thread.run(Thread.java:764)
E/PlayerLayout(19268): onError: 
E/PlayerLayout(19268): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference

**Comment by lecicdjuro** [comment]
@KhuramKhalid , i found a problem. It's HLS url matcher
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/19263556/78967978-ef695f00-7b03-11ea-98ed-b3194b8c74a4.png">

**Comment by KhuramKhalid** [comment]
Good catch. I will update and publish a new version

**Comment by KhuramKhalid** [comment]
Try v1.0.34
