### ISSUE TITLE
Playing A local file

### ISSUE THREAD

**Issue by khashabawy** [muslimtv/flutter_playout#43]
How to Play A local file ?
tried to put a local paths

assets/audio/file.mp3 
/assets/audio/file.mp3 
./assets/audio/file.mp3 
../assets/audio/file.mp3 
.../assets/audio/file.mp3 

and it did not work ?

I also defined the audio folder as an asset in the pubspec
  assets:
    - assets/images/
    - assets/audio/

**Comment by KhuramKhalid** [comment]
Local files aren't supported. It only plays media from URL at the moment.
