### ISSUE TITLE
Does this video player has a controller?

### ISSUE THREAD

**Issue by pratamarama** [muslimtv/flutter_playout#58]
i want to control like start and pausing, seek to position or load another video in the player.

**Comment by KhuramKhalid** [comment]
There isn't as such a controller but you can do these things using the parameters you pass to the player. If the input changes, the player will rebuild. For example you can play, pause the player using `desiredState` which can be either `PLAYING`, `PAUSED` or `STOPPED`. For seek, use `position`. To change/update video, simply update the `url`. Any change in these inputs will trigger the `didUpdateWidget` method that takes care of changing player state to match the new data. See below.

```dart
  @override
  void didUpdateWidget(Video oldWidget) {
    if (widget.url == null || widget.url.isEmpty) {
      _disposePlatformView();
    }
    if (oldWidget.url != widget.url ||
        oldWidget.title != widget.title ||
        oldWidget.subtitle != widget.subtitle ||
        oldWidget.isLiveStream != widget.isLiveStream) {
      _onMediaChanged();
    }
    if (oldWidget.desiredState != widget.desiredState) {
      _onDesiredStateChanged(oldWidget);
    }
    if (oldWidget.showControls != widget.showControls) {
      _onShowControlsFlagChanged();
    }
    if (oldWidget.preferredAudioLanguage != widget.preferredAudioLanguage) {
      _onPreferredAudioLanguageChanged();
    }
    if (oldWidget.position != widget.position && widget.position >= 0) {
      _onSeekPositionChanged();
    }
    super.didUpdateWidget(oldWidget);
  }
```
