### ISSUE TITLE
Programmatic way of playing the hls stream  (.m3u8)

### ISSUE THREAD

**Issue by huxaiphaer** [muslimtv/flutter_playout#74]
Is there a way (Programmatically ) of playing and stopping the stream ?

**Comment by KhuramKhalid** [comment]
For play/pause, the `Video` widget takes a `desiredState` parameter. 

```dart
PlayerState _desiredState = PlayerState.PLAYING;
```

You will have to keep this in your stateful widget, pass it as parameter to the `Video` widget and change its value to play/pause stream. The widget can detect the change and will update the player accordingly. For example to pause stream see below.

```dart
setState(() {
  _desiredState = PlayerState.PAUSED;
});
```
